version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: surni_multiservices
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: motdepasse
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/surni_multiservices
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: motdepasse
      JWT_SECRET: VOTRE_SECRET_JWT
      JWT_EXPIRATION: 86400000
    ports:
      - "8085:8080"
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
